[package]
name = "raydium_sol_price"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18"
solana-sdk = "1.18"
borsh = "0.10"
spl-token = "4.0"
tokio = { version = "1.36", features = ["full"] }

